### ISSUE TITLE
JDBC driver cannot be loaded well when the top namespace isn't ordinary

### ISSUE THREAD

**Issue by sw-jung** [logstash-plugins/logstash-integration-jdbc#31]
- Version: 7.6
- Config File (if you have sensitive info, please remove it):
```
input {
  jdbc {
    jdbc_driver_library => "/path/to/monetdb-jdbc-2.29.jre7.jar"
    jdbc_driver_class => "nl.cwi.monetdb.jdbc.MonetDriver"
    jdbc_connection_string => "jdbc:monetdb://host:port/db"
    jdbc_user => "username"
    jdbc_password => "password"
    schedule => "* * * * *"
    statement => "SELECT * FROM my_table WHERE tracking_column > :sql_last_value"
    use_column_value => true
    tracking_column => "tracking_column"
  }
}

output {
  stdout {}
}
```
- Steps to Reproduce:
  1. Download https://dev.monetdb.org/downloads/Java/monetdb-jdbc-2.29.jre7.jar
  2. Place to any
  3. Run Logstash with the config above
  4. `nl.cwi.monetdb.jdbc.MonetDriver` not loaded with the error below:
```
Error: nl.cwi.monetdb.jdbc.MonetDriver not loaded. Are you sure you've included the correct jdbc driver in :jdbc_driver_library?
Exception: LogStash::PluginLoadingError
Stack: /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-integration-jdbc-5.0.1/lib/logstash/plugin_mixins/jdbc/jdbc.rb:159:in `load_driver'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-integration-jdbc-5.0.1/lib/logstash/inputs/jdbc.rb:273:in `run'
/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:328:in `inputworker'
/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:320:in `block in start_input'
```

There seems to be a bug in jdbc driver loading when the top namespace isn't one of the most common like "com" or "org" (in this case it's "nl").

**Comment by yaauie** [comment]
Workaround: Prefix the name of the driver class with `Java::`.

The driver is loaded by safe-evaling the driver class name in JRuby to resolve the driver class,  and while Jruby provides `com`, `org`, and `net` to route to those common namespaces, it needs an extra hint that we're loading a java class when using a less-common namespace.
